FROM oven/bun:latest
WORKDIR /myapp
ADD . .
RUN bun install
ENV DOMAIN=${DOMAIN}
ENV PHOTO=${PHOTO}
ENV PHOTODELETE=${PHOTODELETE}
ENV PHOTOPOST=${PHOTOPOST}
ENV PHOTO_KEY=${PHOTO_KEY}
ENV SESSION_SECRET=${SESSION_SECRET}
EXPOSE 5173
