const Photo = process.env.PHOTO as string;
const PhotoKey = process.env.PHOTO_KEY as string;
const PhotoDelete = process.env.PHOTODELETE as string;
const PhotoS3Post = process.env.PHOTOS3POST as string;
const Domain = process.env.DOMAIN as string;
const FrontendUrl = process.env.FRONTEND_URL as string;
const SessionKey = process.env.SESSION_SECRET as string;
const PhotoS3 = process.env.PHOTOS3 as string;
const StripeSecretKey = process.env.STRIPE_SECRET_KEY as string;
const StripePublishableKey = process.env.STRIPE_PUBLISHABLE_KEY as string;
const StripeWebhookSecret = process.env.STRIPE_WEBHOOK_SECRET as string;

export const photoPath = () => Photo;
export const photoKeyPath = () => PhotoKey;
export const photoDeletePath = () => PhotoDelete;
export const photoPostPath = () => PhotoS3Post;
export const domainPath = () => Domain;
export const frontendUrlPath = () => FrontendUrl;
export const sessionKeyPath = () => SessionKey;
export const photoS3Path = () => PhotoS3; 
export const stripeSecretKeyPath = () => StripeSecretKey;
export const stripePublishableKeyPath = () => StripePublishableKey;
export const stripeWebhookSecretPath = () => StripeWebhookSecret;