name: "Deploy Production"
on:
  push:
    branches:
      - "main"

env:
  APP_NAME: "adoptme-frontend"

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for tags

      - name: "Get Latest Tag"
        id: tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          DEFAULT_BUMP: patch
          MAJOR_STRING_TOKEN: "#major"
          MINOR_STRING_TOKEN: "feat:"
          PATCH_STRING_TOKEN: "fix:"

      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: |
            🎉 New release ${{ steps.tag.outputs.new_tag }}!
            - Auto-generated from the latest push to `main`
          draft: false
          prerelease: false

  build:
    needs: tag-and-release  # Add dependency on the tag-and-release job
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Log in to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: "Build and push container"
        uses: "docker/build-push-action@v5"
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ needs.tag-and-release.outputs.new_tag }}